### ISSUE TITLE
tldfinder (dns mode)

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/tldfinder#1]
Help menu:

```console
A streamlined tool for discovering TLDs, associated subdomains, and related domain names.

Usage:
  tldfinder [flags]

Flags:
INPUT:
   -d, -domain string[]  domain or list of domains for discovery (file or comma separated)

OPTIONS:
   -s, -sources string[]          specific sources to use for discovery (bufferover,censys,crtsh,dnsrepo,github,netlas,waybackarchive,whoisxmlapi,whoxy)
   -es, -exclude-sources string[] sources to exclude for discovery (bufferover,censys,crtsh,dnsrepo,github,netlas,waybackarchive,whoisxmlapi,whoxy)
   -m, -mode string[]             discovery mode (dns,tld,domain) (default: dns)

OUTPUT:
   -o, -output string       file to write output
   -j, -jsonl               return output in jsonl format

UPDATE:
   -up, -update                 update tldfinder to latest version
   -duc, -disable-update-check  disable automatic tldfinder update check

DEBUG:
   -version  display version of the project
   -silent   dislabe project banner
   -verbose  run project in verbose mode
```

Example run (dns mode):

```bash
# Input option `-d` supports parsing `tld` from the input as well as directly accept tld name, for example:

# ./tldfinder -d goog
# ./tldfinder -d www.pki.goog
# ./tldfinder -d pki.goog
# all above input are treated same and will look for subdomains starting with `.goog` in available sources.

./tldfinder -d pki.goog
 ________   ___  _____         __       
/_  __/ /  / _ \/ __(_)__  ___/ /__ ____
 / / / /__/ // / _// / _ \/ _  / -_) __/
/_/ /____/____/_/ /_/_//_/\_,_/\__/_/   

                     projectdiscovery.io

[INF] Current tldfinder version v0.0.1 (latest)
[INF] Loading provider config from /Users/geekboy/Library/Application Support/subfinder/provider-config.yaml
[INF] Enumerating subdomains for .goog

ocsp.pki.goog
pki-goog.l.goog
pki-goog.l.goog
pki-goog.l.goog
pki-goog.l.goog
web.voice.telephony.goog
crl.pki.goog
pki-goog.l.goog
pki-goog.l.goog
pki-goog.l.goog
pki-goog.l.goog
mqtt.2030.ltsapis.goog
cloud-iot-mqtt.l.goog
crls.pki.goog
pki-goog.l.goog
pki-goog.l.goog
www3.l.goog
www3.l.goog
1p.ca.rogers.rcs.telephony.goog
ca.rogers.rcs.telephony.goog
1p.mx.amx.rcs.telephony.goog
1p-ca-fizz.rcs.telephony.goog
b1.nel.goog
nl.tmobile.rcs.telephony.goog
1p.us.cspire.rcs.telephony.goog
mx-attmexico.rcs.telephony.goog
obihai.telephony.goog
ph.globe.rcs.telephony.goog
1p.us.tmobile.rcs.telephony.goog
co.amx.rcs.telephony.goog
us.att.rcs.telephony.goog
1p.ca.telus.rcs.telephony.goog
mx.telefonica.rcs.telephony.goog
1p.ch.salt.rcs.telephony.goog
1p.us.pfi.rcs.telephony.goog
1p.ca.bell.rcs.telephony.goog
blog-logrocket-com.translate.goog
1p.ch.swisscom.rcs.telephony.goog
www-educba-com.translate.goog
mv-ooredoo.rcs.telephony.goog
spb-kassir-ru.translate.goog

[INF] Found 41 subdomains for .goog in 13 seconds 942 milliseconds
```
```[tasklist]
### Tasks
- [ ] https://github.com/projectdiscovery/tldfinder/issues/4
- [ ] https://github.com/projectdiscovery/tldfinder/issues/5
- [ ] https://github.com/projectdiscovery/tldfinder/issues/6
- [ ] https://github.com/projectdiscovery/tldfinder/issues/7
- [ ] https://github.com/projectdiscovery/tldfinder/issues/8
- [ ] https://github.com/projectdiscovery/tldfinder/issues/9
- [ ] https://github.com/projectdiscovery/tldfinder/issues/10
```
